name: crawl

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths-ignore: ['README.md']
  schedule:
  - cron: '0 6 * * *' # Daily at 6 AM

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - run: |
        go run ./ --full

        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Update: ${timestamp}" || exit 0
        git push

